version: '3.8'

services:
  mysql: 
    image: mysql:latest
    container_name: sales-db
    restart: always
    ports:
      - 8080:8080
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root